# Generated by Django 4.2.2 on 2023-08-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamdatabase',
            name='spam_phone',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
