# Generated by Django 4.2.2 on 2023-08-07 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_alter_spamdatabase_spam_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='contact_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spamdatabase',
            name='spam_countries_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
